<?php

return array(
  'nodes' => [
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "fanchon",
      'key1' => "john wick",
      'key2' => "o'clock brewing",
    ),
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "la ligue noire",
      'key1' => "harry potter",
      'key2' => "stone brewing",
    ),
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "la strasbourgeoise",
      'key1' => "predator",
      'key2' => "hoppy road",
    ),
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "la bourgogne",
      'key1' => "blade",
      'key2' => "birrificio del ducato",
    ),
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "pelot d'hennebon",
      'key1' => "star wars",
      'key2' => "cervezes la pirata",
    ),
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "les canuts",
      'key1' => "terminator",
      'key2' => "zoumaï",
    ),
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "ah que nos pères",
      'key1' => "the rocky horror picture show",
      'key2' => "brouwerij de molen",
    ),
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "la complainte de mandrin",
      'key1' => "saw",
      'key2' => "la minotte",
    ),
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "la blanche hermine",
      'key1' => "taken",
      'key2' => "beavertown",
    ),
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "coupo santo",
      'key1' => "pirates of the carribean",
      'key2' => "sainte cru",
    ),
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "ceux du liban",
      'key1' => "x-men",
      'key2' => "the piggy brewing company",
    ),
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "réveillez vous picards",
      'key1' => "lord of the rings",
      'key2' => "mikkeller",
    ),
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "monsieur de turenne",
      'key1' => "the matrix",
      'key2' => "la débauche",
    ),
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "au 31 du mois d'août",
      'key1' => "back to the future",
      'key2' => "brewdog",
    ),
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "se canto",
      'key1' => "moulin rouge",
      'key2' => "to ol",
    ),
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "le vin gaulois",
      'key1' => "alien",
      'key2' => "wild beer co",
    ),
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "chevaliers de la table ronde",
      'key1' => "die hard",
      'key2' => "naparbier",
    ),
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "le duc de bordeaux",
      'key1' => "king kong",
      'key2' => "popihn",
    ),
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "dans les prisons de nantes",
      'key1' => "mission impossible",
      'key2' => "fierce",
    ),
    array(
      'glyph' => 'KCN',
      'name' => 'temp',
      'code' => "guerre guerre vente vent",
      'key1' => "indiana jones",
      'key2' => "cloudwater brew co",
    ),
  ],
  'types' => [
    array(
      'name' => 'songs',
      'label' => 'Chansons',
      'image' => 'music',
      'field' => 'code',
    ),
    array(
      'name' => 'movies',
      'label' => 'Films',
      'image' => 'video',
      'field' => 'key1',
    ),
    array(
      'name' => 'beers',
      'label' => 'Bières',
      'image' => 'beer',
      'field' => 'key2',
    ),
    array(
      'name' => 'cars',
      'label' => 'Voitures',
      'image' => 'car',
      'field' => null,
    ),
    array(
      'name' => 'places',
      'label' => 'Lieux',
      'image' => 'map-marker-alt',
      'field' => null,
    ),
    array(
      'name' => 'videosgames',
      'label' => 'Jeux Vidéos',
      'image' => 'trophy',
      'field' => null,
    ),
    array(
      'name' => 'art',
      'label' => 'Art',
      'image' => 'palette',
      'field' => null,
    ),
  ],
);
