<?php

return array(
  'nodes' => [
    array(
      'glyph' => 'AEA',
      'name' => 'Anna ESPONA',
      'code' => "dans les prisons de nantes",
      'key1' => "x-men",
      'key2' => "the piggy brewing company",
    ),
    array(
      'glyph' => 'ARZ',
      'name' => 'Anthony RODRIGUEZ',
      'code' => "fanchon",
      'key1' => "john wick",
      'key2' => "o'clock brewing",
    ),
    array(
      'glyph' => 'ATI',
      'name' => 'Alizé TOSI',
      'code' => "le vin gaulois",
      'key1' => "alien",
      'key2' => "fierce",
    ),
    array(
      'glyph' => 'CGI',
      'name' => 'Claire GHIO',
      'code' => "les canuts",
      'key1' => "terminator",
      'key2' => "zoumaï",
    ),
    array(
      'glyph' => 'CSI',
      'name' => 'Charles SANTUCCI',
      'code' => "monsieur de turenne",
      'key1' => "the matrix",
      'key2' => "la débauche",
    ),
    array(
      'glyph' => 'EGA',
      'name' => 'Elodie GARCIA',
      'code' => "la complainte de mandrin",
      'key1' => "saw",
      'key2' => "la minotte",
    ),
    array(
      'glyph' => 'FBS',
      'name' => 'Frédéric BOURGEOIS',
      'code' => "au 31 du mois d'août",
      'key1' => "back to the future",
      'key2' => "brewdog",
    ),
    array(
      'glyph' => 'JDR',
      'name' => 'Jean-Christophe DUVIVIER',
      'code' => "la ligue noire",
      'key1' => "harry potter",
      'key2' => "naparbier",
    ),
    array(
      'glyph' => 'JGT',
      'name' => 'Jennifer GRIMAULT',
      'code' => "ah que nos pères",
      'key1' => "the rocky horror picture show",
      'key2' => "popihn",
    ),
    array(
      'glyph' => 'JRI',
      'name' => 'Jordan RAIMONDI',
      'code' => "la strasbourgeoise",
      'key1' => "predator",
      'key2' => "hoppy road",
    ),
    array(
      'glyph' => 'JRR',
      'name' => 'Jeremy RICHIER',
      'code' => "le duc de bordeaux",
      'key1' => "pirates of the carribean",
      'key2' => "sainte cru",
    ),
    array(
      'glyph' => 'LML',
      'name' => 'Lisa MARECHAL',
      'code' => "la blanche hermine",
      'key1' => "mission impossible",
      'key2' => "beavertown",
    ),
    array(
      'glyph' => 'MMA',
      'name' => 'Mathias MONTAGNA',
      'code' => "la bourgogne",
      'key1' => "indiana jones",
      'key2' => "birrificio del ducato",
    ),
    array(
      'glyph' => 'PLA',
      'name' => 'Pierre LANTERNA',
      'code' => "réveillez vous picards",
      'key1' => "lord of the rings",
      'key2' => "cloudwater brew co",
    ),
    array(
      'glyph' => 'VKI',
      'name' => 'Vincent KORNYELI',
      'code' => "pelot d'hennebon",
      'key1' => "star wars",
      'key2' => "cervezes la pirata",
    ),
  ],
  'types' => [
    array(
      'name' => 'songs',
      'label' => 'Chansons',
      'image' => 'music',
      'field' => 'code',
    ),
    array(
      'name' => 'movies',
      'label' => 'Films',
      'image' => 'video',
      'field' => 'key1',
    ),
    array(
      'name' => 'beers',
      'label' => 'Bières',
      'image' => 'beer',
      'field' => 'key2',
    ),
    array(
      'name' => 'cars',
      'label' => 'Voitures',
      'image' => 'car',
      'field' => null,
    ),
    array(
      'name' => 'places',
      'label' => 'Lieux',
      'image' => 'map-marker-alt',
      'field' => null,
    ),
    array(
      'name' => 'videosgames',
      'label' => 'Jeux Vidéos',
      'image' => 'trophy',
      'field' => null,
    ),
    array(
      'name' => 'art',
      'label' => 'Art',
      'image' => 'palette',
      'field' => null,
    ),
  ],
);
